### ISSUE TITLE
market and duke dataset  can't download 

### ISSUE THREAD

**Issue by lisuichan** [vana77/Bottom-up-Clustering-Person-Re-identification#2]
Hi, thank you for share your code. I want to run your code, but I found the link to market dataset is invalid now, can you check it  and share a new link . Thank you!

**Comment by vana77** [comment]
Hi @lisuichan , thanks. I just updated the download link.

**Comment by Mickeybaby** [comment]
@lisuichan 
Hi,
When I run the sh ./run.sh:
(bottom-up-reID) mickey@a208-System-Product-Name:/Bottom-up-Clustering-Person-Re-identification$ python --versionPython 3.6.0 :: Continuum Analytics, Inc.
(bottom-up-reID) mickey@a208-System-Product-Name:/Bottom-up-Clustering-Person-Re-identification$ sh ./run.sh
Traceback (most recent call last):
File "run.py", line 2, in 
from reid.bottom_up import *
File "/home/mickey/Bottom-up-Clustering-Person-Re-identification/reid/init.py", line 6, in 
from . import metric_learning
File "/home/mickey/Bottom-up-Clustering-Person-Re-identification/reid/metric_learning/init.py", line 3, in 
from metric_learn import (ITML_Supervised, LMNN, LSML_Supervised,
File "/home/mickey/miniconda3/envs/bottom-up-reID/lib/python3.6/site-packages/metric_learn/init.py", line 8, in 
from .sdml import SDML, SDML_Supervised
File "/home/mickey/miniconda3/envs/bottom-up-reID/lib/python3.6/site-packages/metric_learn/sdml.py", line 15, in 
from sklearn.utils.extmath import pinvh
ImportError: cannot import name 'pinvh'
Can you give me some advice ?
Best wishes to you!

**Comment by lisuichan** [comment]
Maybe you need to install the 'pinvh'.  But in my case, I just comment the line 'from metric_learn import (ITML_Supervised, LMNN, LSML_Supervised ... '  and related lines, maybe it is helpful to you too。@Mickeybaby

**Comment by Mickeybaby** [comment]
@lisuichan Thank you.I solved it.
